services:
  # 1. Cơ sở dữ liệu: TimescaleDB
  stationmonitor-db:
    image: timescale/timescaledb:latest-pg16
    container_name: stationmonitor-db
    restart: always
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=stationmonitor
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  # 2. MQTT Broker
  stationmonitor-mqtt:
    image: eclipse-mosquitto:latest
    container_name: stationmonitor-mqtt
    restart: always
    network_mode: host
    volumes:
      - ./data/mosquitto/config:/mosquitto/config
      - ./data/mosquitto/data:/mosquitto/data
      - ./data/mosquitto/log:/mosquitto/log

  # 3. Video Streaming: go2rtc
  stationmonitor-streaming:
    image: alexxit/go2rtc:latest
    container_name: stationmonitor-streaming
    restart: always
    network_mode: host
    volumes:
      - ./media-server/go2rtc.yaml:/config/go2rtc.yaml

  # 4. Backend chính: StationMonitor ASP.NET Core API
  stationmonitor-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stationmonitor-backend
    restart: always
    network_mode: host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings__Default=Host=localhost;Port=5432;Database=stationmonitor;Username=postgres;Password=postgres123"
      - "Mqtt__Broker=localhost"
      - "Jwt__Key=StationMonitor_SuperSecret_Key_2026_ChangeInProduction!"
      - "Go2Rtc__ApiUrl=http://localhost:1984"
      - "Go2Rtc__RtspUrl=rtsp://localhost:8554"
      - "Media__FFmpegPath=ffmpeg"
      - "Security__TrustedNetworks=127.0.0.1,172.,192.168."
    volumes:
      - ./data/media:/app/wwwroot/media
      - ./data:/app/data

#  # 5. AI Engine
#  stationmonitor-ai:
#    build:
#      context: ./sdk-relay
#      dockerfile: Dockerfile
#    container_name: stationmonitor-ai
#    restart: always
#    network_mode: host
#    environment:
#      - CAMERA_IP=192.168.10.152
#      - CAMERA_USER=admin
#      - CAMERA_PASSWORD=Demo@2024
#      - API_URL=http://localhost:5056/api/v1
#      - GO2RTC_RTSP_URL=rtsp://localhost:8554
#      - WWWROOT_PATH=/app/data/media
#    volumes:
#      - ./data/media:/app/wwwroot/media
#      - ./sdk-relay:/app
